modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="siren_head"
version="1.0.4"
displayName="Siren head mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Jed, MCreator"
description='''
This is my siren head mod. Hope you like
'''

[[dependencies.siren_head]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




